import Head from 'next/head'
import Footer from '../components/Footer'
import FormSignUp from '../components/FormSignUp'
import NavBar from '../components/NavBar'



export default function Login() {
  return (
    <>
      <Head>
        <title>SignUp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <FormSignUp/>
    </>
  )
}
