import Head from 'next/head'
import NavBar from './components/NavBar'
import Header from './components/Header'
import React from 'react'
import Footer from './components/Footer'
import useAppContext from './contexts/appContext'
import Product from './components/Product'
import { Container, SimpleGrid } from '@chakra-ui/react'

export default function Home() {
  const { products } = useAppContext();
  
  return (
    <>
      <Head>
        <title>GCP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Header />
      <Container maxW="container.xl" bg="gray.100" py={5}>
      {
        !!products && // Validar que exista la variable o datos
        products.length > 0 &&
        products.map(({ name, id, gender, url, index }) => {
          return (

            <Product name={name} gender={gender} url={url} id={id} index={index} />
          );
        })
      }
      </Container>
      <Footer/>
    </>
  )
}
