
import Head from 'next/head';
import FormSignIn from '../components/FormSignIn';
import NavBar from '../components/NavBar';

export default function SingIn() {
  return (
    <>
      <Head>
        <title>SyD:SignIn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <FormSignIn/>
    </>
  );
}