import Head from 'next/head'
import React from 'react'
import NavBar from '../components/NavBar'
import Footer from '../components/Footer'
import { Box, Container, Heading, Stack, Text } from '@chakra-ui/react'
import CardContact from '../components/CardContact'

const AboutUs = () => {
    const card = [
        {
            title: 'Design Projects 1',
            text: "The project board is an exclusive resource for contract work. It's perfect for freelancers, agencies, and moonlighters.",
            image:
                'https://images.unsplash.com/photo-1516796181074-bf453fbfa3e6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDV8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=900&q=60',
        },]
    return (
        <>
            <Head>
                <title>GCD:About Us</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <NavBar />
            <Box
                height={'xl'}
                position="relative"
                backgroundPosition="center"
                backgroundRepeat="no-repeat"
                backgroundSize="cover"
                backgroundImage={'https://thumbs.dreamstime.com/z/chemistry-vector-banner-chemical-equipment-chemical-experiences-68814517.jpg'}>
                {/* This is the block you need to change, to customize the caption */}
                <Container size="container.lg" height="600px" position="relative">
                    <Stack
                        spacing={6}
                        w={'full'}
                        maxW={'lg'}
                        position="absolute"
                        top="50%"
                        transform="translate(0, -50%)">
                        <Heading fontSize={{ base: '3xl', md: '4xl', lg: '5xl' }} >
                            GCP
                        </Heading>

                    </Stack>

                </Container>
            </Box>
            <Container as={Stack} maxW={'6xl'} py={10}>
                <Heading>¿Quienes Somos?</Heading>
                <Text py={3} fontSize='xl'>Exercitation dolore velit consequat aliqua reprehenderit velit excepteur et excepteur Lorem labore do exercitation. Ut minim ex consectetur aute velit ut aute do irure. Velit non laborum adipisicing exercitation elit minim cupidatat qui dolore magna nisi adipisicing aliquip. Et id velit aliqua incididunt aliqua reprehenderit elit ex mollit cupidatat. Ullamco mollit velit sunt incididunt nulla voluptate consectetur.</Text>
            </Container>
            <CardContact />
            <Footer />
        </>
    )
}

export default AboutUs